### ISSUE TITLE
This snow melt need to be stored in water2pool

### ISSUE THREAD

**Issue by LeoGooga** [CryoGrid/CryoGrid3#9]
https://github.com/CryoGrid/CryoGrid3/blob/cd214218410598825fcf642d06941d37eb52a325/modules/cryoGridSnow/updateGRID_snow.m#L148

add here :
GRID.soil.water2pool = GRID.soil.water2pool + ( GRID.snow.Snow_i(GRID.snow.cT_domain_ub) + GRID.snow.Snow_w(GRID.snow.cT_domain_ub) );

**Comment by jannitzbon** [comment]
Yep, this seems to be correct. We store the snowmelt occuring from the "melt" function in CryoGridSnow.m temporary within GRID.soil.water2pool. So we should do the same here.
